baseurl: /
languageCode: en-us
theme: terminal
paginate: 10
pluralizeListTitles: false
googleAnalytics: G-TS08N0RL86

params:
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName: blog

  # ["orange", "blue", "red", "green", "pink"]
  themeColor: red

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 6

  # show selector to switch language
  showLanguageSelector: false

  # set theme to full screen width
  fullWidthTheme: false

  # center theme with default width
  centerTheme: true

  # set a custom favicon (default is a `themeColor` square)
  # favicon: "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated: false
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix: "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize: false

  twitter:
    # set Twitter handles for Twitter cards
    # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
    # do not include @
    creator: "jldevezas"
    site: "http://www.josedevezas.com/"

languages:
  en:
    languageName: "English"
    title: "José Devezas, PhD"
    subtitle: "PhD in Computer Science"
    owner: "José Devezas"
    keywords: ""
    copyright: "&copy; 2021-2023 José Devezas"
    menuMore: "Show more"
    readMore: "Read more"
    readOtherPosts: "Read other posts"
    missingContentMessage: "Page not found..."
    missingBackButtonLabel: "Back to home page"

    params:
      logo:
        logoText: "José Devezas, PhD"
        logoHomeLink: "/"

    menu:
      main:
      - identifier: "home"
        name: "Home"
        url: "/"
        weight: -120
      - identifier: "blog"
        name: "Blog"
        url: "/blog"
        weight: -110
      - identifier: "academy"
        name: "Academy"
        url: "/academy"
        weight: -100
      - identifier: "career"
        name: "Career"
        url: "/career"
        weight: -90
      - identifier: "about"
        name: "About"
        url: "/about"
        weight: -80
      - identifier: "contact"
        name: "Contact"
        url: "/contact"
        weight: -70
      - identifier: "tags"
        name: "Tags"
        url: "/tags"
        weight: -60
      - identifier: "rss"
        name: "RSS"
        url: "/blog/index.xml"
        weight: -50
